# Numpy Questions

### Q.1) Create a numpy array in python?

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("Array:",arr)

Array: [1 2 3 4 5 6]


### Q.2) Write a program that takes in a NumPy array and returns its mean?

In [8]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("Array:",arr)
print("Mean:",np.mean(arr))

Array: [1 2 3 4 5 6]
Mean: 3.5


### Q.3) Write a program that takes in a NumPy array and returns its shape?

In [11]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("Array:",arr)
print("Shape:",np.shape(arr))

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)


### Q.4) How can we convert a list into numpy array?

In [14]:
import numpy as np
l=[1,2,3,4,5,6]
print("List:",l)
arr=np.array(l)
print("Array:",arr)

List: [1, 2, 3, 4, 5, 6]
Array: [1 2 3 4 5 6]


### Q.5) Creates a NumPy array filled with zeros of 3X3 size?

In [18]:
import numpy as np
arr = np.zeros((3,3))
print("Array:",arr)

Array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q.6)  Creates a NumPy array filled with ones of mXn size?

In [22]:
import numpy as np
import random as rn
m,n=rn.randint(0,10),rn.randint(0,10)
print(f'm: {m}, n: {n}')
arr = np.ones((m,n))
print("Array:",arr)

m: 3, n: 6
Array: [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


### Q.7) Creates a NumPy array filled with random values between 0 and 1.

In [26]:
import numpy as np
m,n=rn.randint(0,10),rn.randint(0,10)
print(f'm: {m}, n: {n}')
arr = np.random.rand(m,n)
print("Array:",arr)

m: 7, n: 2
Array: [[0.46046268 0.64596566]
 [0.88196999 0.99659038]
 [0.33155638 0.11021305]
 [0.48960625 0.87660322]
 [0.13446221 0.27111099]
 [0.16025779 0.74412516]
 [0.87756029 0.98662471]]


### Q.8)  Creates a NumPy array with a range of values?

In [28]:
import numpy as np
m,n,r=rn.randint(0,10),rn.randint(10,31),rn.randint(0,5)
print(f'start: {m}, end: {n},step: {r}')
arr = np.arange(m,n,r)
print("Array:",arr)

start: 2, end: 15,step: 4
Array: [ 2  6 10 14]


### Q.9) How to reshape a NumPy array to a new shape?

In [32]:
import numpy as np
arr = np.arange(1, 10)
print("Original array:")
print(arr)
new_arr = np.reshape(arr, (3,3))
print("Reshaped array:")
print(new_arr)

Original array:
[1 2 3 4 5 6 7 8 9]
Reshaped array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Q.10) Computes the sum of all the elements in a NumPy array?

In [33]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("Array:",arr)
print("Sum:",np.sum(arr))

Array: [1 2 3 4 5 6]
Sum: 21


### Q.11) Computes the standard deviation of all the elements in a NumPy array.

In [37]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("Array:",arr)
print("Standard Deviation:",np.std(arr))

Array: [1 2 3 4 5 6]
Standard Deviation: 1.707825127659933


### Q.12) Computes the dot product of two NumPy arrays.


In [39]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])
print(f'Array 1: {arr1}\nArray 2: {arr2}')
print("Dot Product:",np.dot(arr1,arr2))

Array 1: [1 2 3 4 5 6]
Array 2: [ 7  8  9 10 11 12]
Dot Product: 217


### Q.13) Create a 2D NumPy array with shape (3, 3) containing all zeros?

In [40]:
import numpy as np
arr = np.zeros((3,3))
print("Array:",arr)

Array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q.14) Create a 1D numpy array containing the values from -10 to 10, with a step of 2.


In [42]:
import numpy as np
m,n,r=-10,10,2
print(f'start: {m}, end: {n}, step: {r}')
arr = np.arange(m,n,r)
print("Array:",arr)

start: -10, end: 10, step: 2
Array: [-10  -8  -6  -4  -2   0   2   4   6   8]


### Q.15) Create a 2D numpy array with shape (3, 3) containing random values between 0 and 1. Then, set all values in the first row to 0.

In [49]:
import numpy as np
arr = np.random.rand(3,3)
print("Array:",arr)
print("\nArray with 1st row as 0:")
arr[0]=0
print(arr)

Array: [[0.29111962 0.00596916 0.066732  ]
 [0.12937335 0.40321775 0.34842048]
 [0.68225634 0.64732921 0.66508253]]

Array with 1st row as 0:
[[0.         0.         0.        ]
 [0.12937335 0.40321775 0.34842048]
 [0.68225634 0.64732921 0.66508253]]


### Q.16) Create a 1D numpy array containing the values from 0 to 9. Then, create a new array containing the values squared.

In [52]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
sq_arr=np.square(arr)
print(f'Array: {arr}\nSquare Array: {sq_arr}')

Array: [0 1 2 3 4 5 6 7 8 9]
Square Array: [ 0  1  4  9 16 25 36 49 64 81]


### Q.17) Create a 1D numpy array containing the values from 1 to 10. Then, extract all even values from the array.

In [54]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(f'Array: {arr}')
for i in arr:
    print(i)

Array: [ 1  2  3  4  5  6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10


### Q.18) Create a 1D numpy array containing the values from 1 to 10. Then, extract all odd values from the array.

In [55]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(f'Array: {arr}')
for i in arr:
    if (i%2!=0):
          print(i)

Array: [ 1  2  3  4  5  6  7  8  9 10]
1
3
5
7
9


### Q.19)Create a 2D numpy array with shape (3, 3) containing random values between 0 and 1. Then, compute the mean of each row.

In [56]:
import numpy as np
arr = np.random.rand(3,3)
print("Array:",arr)
print(f'Mean of 1st row: {np.mean(arr[0])}, 2nd row: {np.mean(arr[1])}, 3rd row: {np.mean(arr[2])}')

Array: [[0.73004107 0.09441404 0.82969614]
 [0.52209878 0.67352678 0.427532  ]
 [0.48038314 0.06400301 0.99704194]]
Mean of 1st row: 0.5513837498661613, 2nd row: 0.5410525199088555, 3rd row: 0.5138093628035331


### Q.20) How to split numpy array into 3 parts?
#### arr = np.array([1, 2, 3, 4, 5, 6])

In [58]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]
